import React, { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { JhiItemCount, JhiPagination, TextFormat, Translate, getPaginationState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSort, faSortDown, faSortUp } from '@fortawesome/free-solid-svg-icons';
import { APP_DATE_FORMAT } from 'app/config/constants';
import { ASC, DESC, ITEMS_PER_PAGE, SORT } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities } from './analysis-report.reducer';
import { CSVLink } from 'react-csv'; // لتصدير البيانات إلى CSV

export const AnalysisReport = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();

  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getPaginationState(pageLocation, ITEMS_PER_PAGE, 'id'), pageLocation.search),
  );

  const [titleFilter, setTitleFilter] = useState(''); // لتصفية العنوان
  const [statusFilter, setStatusFilter] = useState(''); // لتصفية الحالة
  const [filteredData, setFilteredData] = useState([]); // البيانات المصفاة

  const analysisReportList = useAppSelector(state => state.gateway.analysisReport.entities);
  const loading = useAppSelector(state => state.gateway.analysisReport.loading);
  const totalItems = useAppSelector(state => state.gateway.analysisReport.totalItems);

  // إعداد أعمدة CSV
  const headers = [
    { label: 'ID', key: 'id' },
    { label: 'Title', key: 'title' },
    { label: 'Created At', key: 'createdAt' },
    { label: 'Analysis Type', key: 'analysisType' },
    { label: 'Report Type', key: 'reportType' },
    { label: 'Generated By', key: 'generatedBy' },
    { label: 'Content', key: 'content' },
    { label: 'Status', key: 'status' },
  ];

  const getAllEntities = () => {
    dispatch(
      getEntities({
        page: paginationState.activePage - 1,
        size: paginationState.itemsPerPage,
        sort: `${paginationState.sort},${paginationState.order}`,
      }),
    );
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (pageLocation.search !== endURL) {
      navigate(`${pageLocation.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(pageLocation.search);
    const page = params.get('page');
    const sort = params.get(SORT);
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [pageLocation.search]);

  useEffect(() => {
    let filtered = analysisReportList;
    if (titleFilter) {
      filtered = filtered.filter(item => item.title && item.title.toLowerCase().includes(titleFilter.toLowerCase()));
    }
    if (statusFilter) {
      filtered = filtered.filter(item => item.status && item.status.includes(statusFilter));
    }
    setFilteredData(filtered);
  }, [analysisReportList, titleFilter, statusFilter]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === ASC ? DESC : ASC,
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const getSortIconByFieldName = (fieldName: string) => {
    const sortFieldName = paginationState.sort;
    const order = paginationState.order;
    if (sortFieldName !== fieldName) {
      return faSort;
    }
    return order === ASC ? faSortUp : faSortDown;
  };

  return (
    <div>
      <h2 id="analysis-report-heading" data-cy="AnalysisReportHeading">
        <Translate contentKey="gatewayApp.analyticsAnalysisReport.home.title">Analysis Reports</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="gatewayApp.analyticsAnalysisReport.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <CSVLink data={filteredData} headers={headers} filename="analysis-reports.csv" className="btn btn-success">
            <FontAwesomeIcon icon="file-export" /> Export to CSV
          </CSVLink>
          <Link to="/analysis-report/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="gatewayApp.analyticsAnalysisReport.home.createLabel">Create new Analysis Report</Translate>
          </Link>
        </div>
      </h2>

      {/* واجهة التصفية */}
      <div className="mb-3">
        <input
          type="text"
          placeholder="Filter by Title"
          value={titleFilter}
          onChange={e => setTitleFilter(e.target.value)}
          className="form-control me-2"
          style={{ display: 'inline', width: '200px' }}
        />
        <input
          type="text"
          placeholder="Filter by Status"
          value={statusFilter}
          onChange={e => setStatusFilter(e.target.value)}
          className="form-control"
          style={{ display: 'inline', width: '200px' }}
        />
      </div>

      <div className="table-responsive">
        {filteredData && filteredData.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="gatewayApp.analyticsAnalysisReport.id">ID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('id')} />
                </th>
                <th className="hand" onClick={sort('title')}>
                  <Translate contentKey="gatewayApp.analyticsAnalysisReport.title">Title</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('title')} />
                </th>
                <th className="hand" onClick={sort('createdAt')}>
                  <Translate contentKey="gatewayApp.analyticsAnalysisReport.createdAt">Created At</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('createdAt')} />
                </th>
                <th className="hand" onClick={sort('analysisType')}>
                  <Translate contentKey="gatewayApp.analyticsAnalysisReport.analysisType">Analysis Type</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('analysisType')} />
                </th>
                <th className="hand" onClick={sort('reportType')}>
                  <Translate contentKey="gatewayApp.analyticsAnalysisReport.reportType">Report Type</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('reportType')} />
                </th>
                <th className="hand" onClick={sort('status')}>
                  <Translate contentKey="gatewayApp.analyticsAnalysisReport.status">Status</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('status')} />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {filteredData.map((analysisReport, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/analysis-report/${analysisReport.id}`} color="link" size="sm">
                      {analysisReport.id}
                    </Button>
                  </td>
                  <td>{analysisReport.title}</td>
                  <td>
                    {analysisReport.createdAt ? <TextFormat type="date" value={analysisReport.createdAt} format={APP_DATE_FORMAT} /> : null}
                  </td>
                  <td>
                    <Translate contentKey={`gatewayApp.AnalysisType.${analysisReport.analysisType}`} />
                  </td>
                  <td>
                    <Translate contentKey={`gatewayApp.ReportType.${analysisReport.reportType}`} />
                  </td>
                  <td>
                    <Translate contentKey={`gatewayApp.Status.${analysisReport.status}`} />
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/analysis-report/${analysisReport.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/analysis-report/${analysisReport.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        onClick={() =>
                          (window.location.href = `/analysis-report/${analysisReport.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`)
                        }
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="gatewayApp.analyticsAnalysisReport.home.notFound">No Analysis Reports found</Translate>
            </div>
          )
        )}
      </div>
      {totalItems ? (
        <div className={analysisReportList && analysisReportList.length > 0 ? '' : 'd-none'}>
          <div className="justify-content-center d-flex">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </div>
          <div className="justify-content-center d-flex">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={totalItems}
            />
          </div>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

export default AnalysisReport;
